config/routes.rb
Me::Application.routes.draw do
  root :to => 'static_pages#about'

  match "/about",   to: "static_pages#about"

  match "/resume",  to: "static_pages#resume"

  match "/contact", to: "static_pages#contact"

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def resume
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chenoa Siegenthaler | <%= yield(:title) %></title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>
  <body>
     <header class="navbar navbar-fixed-top navbar-inverse">
        <div class="navbar-inner">
          <div class="container">
            <%= link_to "Chenoa Siegenthaler", about_path, id: "logo" %>
            <nav>
              <ul class="nav pull-right">
                <li><%= link_to "About",     about_path %></li>
                <li><%= link_to "Resume",    resume_path %></li>
                <li><%= link_to "Contact",   contact_path %></li>
              </ul>
            </nav>
          </div>
        </div>
      </header>
      <div class="container">
        <%= yield %>
      </div>
  
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide :title, "About" %>

<div id="content">
  <h1>About Chenoa</h1>

  <p>Chenoa practices martial arts, enjoys backpacking and loves the color-gradient of the sky at dawn and dusk.</p>
</div>

app/views/static_pages/contact.html.erb
<% provide :title, "Contact" %>

<div id="content">
  <h1>Contact Chenoa</h1>
  <p><a href="mailto:chenoa.siegenthaler@gmail.com">chenoa.sieg@gmail.com</a></p>
</div>

app/views/static_pages/resume.html.erb
<% provide :title, "Resume" %>

<div id="resume" class="center narrow">
  <h1 class="text-center">Chenoa N. Siegenthaler</h1>
  <a href="mailto:chenoa.siegenthaler@gmail.com">chenoa.sieg@gmail.com</a>
  <h2 class="text-center">Work Experience</h2>


  <p><b>Gardener, Oakland, CA</b></p>
  <p>5/3/2012 - present</p>
  <ul>
    <li>Communication with clients regarding desired look and cost of garden</li>
    <li>Plant cultivation: watering, covering with mulch, fertilizing, transplanting and pruning.</li>
    <li>Identifying and removing unwanted plants from garden areas.</li>
    <li>Building garden beds: digging and aerating soil, removing rocks, filling with soil and compost.</li>
    <li>Selecting and planting new plants.</li>
    <li>Moving heavy objects – bags of soil and compost, large pots and planter boxes, rocks and bricks.</li>
    <li>Construction of small rock retaining walls and pathways.</li>
  </ul>


  <p><b>Self-Employed Web Developer</b></p>
  <p>10/2012 - present</p>
  <ul>
    <li>Building a WordPress site (http://www.priestlakefloraldesign.com) for a floral designer</li>
    <li>Communicating with the floral designer in the process of development regarding layout, content, usability and appearance</li>
    <li>Selecting and editing photos to represent the work of the floral design business</li>
    <li>Search-engine optimization for the site</li>
  </ul>


  <p><b>Programming Intern, Hedgeye Risk Management, New Haven, CT</b></p>
  <p>5/23/2011 – 2/3/2012, 40 hours/week</p>
  <ul>
    <li>Computer software development and programming.</li>
    <li>Assisting with two redesigns of the company’s Web site.</li>
    <li>Working in a team environment, with daily group discussion of planned tasks, code review, and pair programming.</li>
    <li>Adding features and repairing bugs for the company’s Web application, using programming languages Ruby, Rails, Javascript, HTML and CSS.</li>
    <li>Quality-assurance testing of Rails-based Web applications, using manual techniques and writing automated tests using Ruby’s RSpec testing library and Selenium, a browser automation engine.</li>
    <li>Tracking bugs with highly detailed descriptions, using Pivotal Tracker.</li>
  </ul>


  <p><b>Retail Salesperson, Edge of the Woods Natural Market, New Haven, CT (Vitamin Department)</b></p>
  <p>1/2007 – 5/2012, 22 – 35 hours/week while studying Martial Arts/Computer Programming</p>
  <ul>
    <li>Assisting customers with finding products to suit their needs.</li>
    <li>Developing a broad knowledge of products in order to inform customers and sell products.</li>
    <li>Operating cash register, counting and balancing cash drawer.</li>
    <li>Regulating and keeping track of many demands in a busy, high­stress environment.</li>
    <li>Keeping inventory of six lines of product, staying in contact with sales representatives, ordering and placing special orders when requested by customers.</li>
    <li>Coordinating tasks and communicating with other members of team.</li>
  </ul>

  
  <p><b>Fishway Operator, Norwich Public Utilities, Norwich, CT</b></p>
  <p>4/18/2008 - 12/7/2008, 40 hours/week</p>
  <ul>
    <li>Monitoring four different fishways - two fish ladders and two fish lifts; recording fish numbers, species and activity for a study by the CT Dept. of Environmental Protection.</li>
    <li>Operating fish lifts.</li>
    <li>Observing and recording fish activity in water above and below dams.</li>
    <li>Creating Excel spreadsheets to document timing, numbers and species of fish that were using the fishways.</li>
    <li>Compiling a report containing detailed written descriptions, video excerpts, and graphs of fish activity for spring and fall seasons.</li>
  </ul>


  <p><b>Restoration Worker, Yosemite National Park, CA</b></p>
  <p>Seasonal (3­6 months each year), 40 hours/week, 2002 – 2006</p>
  <ul>
    <li>Hiking into the wilderness for 4-8 days at a time, carrying all required food, survival gear and tools.</li>
    <li>Restoration and reduction of campsites and other high-impact areas: removal of illegal fire rings, loosening of compacted soil, placement of logs, branches and duff to disguise and discourage further use of the area.</li>
    <li>Identifying and removing invasive non-native plants such as blackberry, mullein and salsify.</li>
    <li>Using GPS technology to map deep trail ruts, campsites and invasive plants.</li>
    <li>Building a split-rail fence to discourage further impact along a riverbank.</li>
    <li>Planting of willow, grass and moss along the banks of two rivers that had been heavily impacted.</li>
    <li>Removal of remaining refuse, including possibly asbestos-laden pipe fragments, from an old dump site.</li>
    <li>Occasional work with volunteers on large restoration projects such as tree removal in meadows and collection of native grass seeds.</li>
    <li>Excellence in Service award, 2002.</li>
    <li>Heart Saver first aid training, 2006.</li>
    <li>Defensive driving certification, 2006.</li>
    <li>Chainsaw and Crosscut Saw certification, 2006.</li>
  </ul>


  <p><b>Conservation Intern, Mammoth Cave National Park , KY</p></b>
  <p>10/-01 - 12/01, 3/02 - 6/02; internship sponsored by the Student Conservation Association</p>
  <ul>
    <li>Lesser Cave Inventory: searching for caves in the forest based on reports by public and previous researchers, while carrying a gas-powered hammer drill and GPS equipment.</li>
    <li>Obtaining cave entrance positions with GPS technology.</li>
    <li>Conducting surveys of cave layout and wildlife.</li>
    <li>Drilling holes in rock at cave entrance, using gas-powered hammer drill, in which to place metal caps in to serve as identification.</li>
    <li>Restoration of an old road bed: decompaction of soil, laying erosion-control mat and duff over surface of the former road.</li>
    <li>Restoration of a former theme park: removing refuse and knocking down buildings.</li>
    <li>Removal of a concrete wall and walkway from a cave entrance, using a gas-powered hammer drill and driving an all-terrain vehicle pulling a trailer full of concrete fragments two miles to the nearest road.</li>
    <li>Removal of old pieces of walkway from inside the cave.</li>
    <li>Removal of non-native, invasive garlic mustard, using a weed whacker.</li>
  </ul>


  <p><b>Other work experience includes:</b></p>
  <ul>
    <li>Gardener, Branford, CT</li>
    <li>Cashier, Atticus Books, New Haven, CT</li>
    <li>Wellness Center Manager, Antioch College, Yellow Springs, OH</li>
    <li>Office Assistant, Antioch College Community Government</li>
    <li>Assistant to a private gardener with a business focusing on organic and native plant cultivation, Oakland area, CA</li>
  </ul>

  <p><b>Education</b></p>
  <p>Completed 3 years of study at Antioch College, Yellow Springs, Ohio; coursework including ecology, calculus, physics, chemistry, geology, anthropology, and psychology.</p>
  <p>2002-2005</p>
  <p>Student of Tai Chi since 2002, and Kung Fu, Aikido, Silat and Systema since 2005; I have some teaching experience, and am continuing to work towards greater proficiency, studying with several different teachers.</p>
  <p>Graduated from San Francisco Waldorf High School, San Francisco, CA 6/16/2001</p>


  <p><b>Volunteer Experience</b></p>
  <ul>
    <li>Tutored children ages 7 - 10 in reading in New Haven, CT for three months starting Feb. 2012</li>
    <li>Assistant youth leader at Montclair Presbyterian Church in Oakland, CA since 10/2012</li>
    <li>Yosemite National Park: working at Yosemite Valley Visitor Center desk, answering phones and roving campgrounds to check in with campers and ensure their compliance with bear regulations.</li>
    <li>Part of a core planning group of an organization to support women programmers, Women Who Code, in San Francisco; participation includes teaching beginner/intermediate programmers and developing a structured project for intermediate programmers to work on to improve skills.</li>
  </ul>

  <p><b>Computer Expertise</b></p>
  <ul>
    <li>Development of computer programs using the Ruby language; Web development using programming languages Ruby on Rails, Javascript, HTML and CSS.</li>
    <li>Wordpress</li>
    <li>Microsoft Office, mainly Word and Excel</li>
    <li>Operating Systems: Windows, Mac OS X, Ubuntu Linux</li>
    <li>Easily learn to use new programs as a result of years of experience using various types of computers and many different programs, including data-entry programs, web browsers, and GIS programs.</li>
  </ul>
  
  
  <p><b>Other Skills and Activities</b></p>
  <ul>
    <li>Participation in San Francisco’s Women Who Code organization, including being part of the core planning group, and developing a coding sprint for members of the group who are intermediate Ruby developers hoping to learn Rails.</li>
    <li>Practicioner of martial arts, including Kung Fu, Tai Chi, Aikido, Silat and Systema since 2002.</li>
    <li>Extensive camping and backpacking expertise, with experience starting at an early age.</li>
    <li>Experience with rock climbing and trail running</li>
    <li>Proficiency in German; some Spanish and Japanese as well</li>
    <li>Guitar and violin - specializing primarily in folk music</li>
    <li>Practitioner of meditation</li>
    <li>Art - mainly drawing, some watercolor and photography</li>
    <li>Creative writing - songs, poetry, stories, essays</li>
  </ul>
</div>